/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFiles;

import ExternalJavaFiles.Database;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import scmv.ChangePassword;
import scmv.Dashboard;
import scmv.ForgetPassword;
import scmv.GoodBye;
import scmv.SignInUp;

/**
 *
 * @author farzeen
 */
public class BrowseJavaPackage extends javax.swing.JFrame {

    /**
     * Creates new form BrowseJavaPackage
     */
     DefaultTableModel modl;
    
        Connection con=null;
        ResultSet rs=null;
        PreparedStatement pstm=null;
    public static String selected=null;
    public  static String fileName;
    public String selectedPackageName;
    DefaultListModel m= new DefaultListModel();
    List<String> alist= new ArrayList<String>();
    
    public BrowseJavaPackage() {
        initComponents();
        openDBConnection();
        selected=null;
        fileName=null;
        selectedPackageName=null;
          BarPanel.setVisible(false);    
        
    }
   public BrowseJavaPackage(String PCKName) {
        initComponents();
        selectedPackageName=PCKName;
        selected=null;
        fileName=null;
        openDBConnection(); 
        selectJavaPackage();
          BarPanel.setVisible(false);    
        
    }
     public void AlertMessage(String message,String path,String title){
            ImageIcon icon = new ImageIcon(path);
            JPanel panel = new JPanel();
            Border blackline = BorderFactory.createLineBorder(Color.black);
            panel.setBorder(blackline);
            panel.setBackground(new Color(169,224,49));
            panel.setSize(new Dimension(200, 64));
            panel.setLayout(null);

            JLabel label = new JLabel(message);
            label.setBounds(0, 0, 200, 64);
            label.setFont(new Font("Arial", Font.BOLD, 12));
            label.setHorizontalAlignment(SwingConstants.CENTER);
            panel.add(label);

            UIManager.put("OptionPane.minimumSize",new Dimension(300, 120));
            UIManager.put("RootPane.DialogBorder", new LineBorder(Color.black));
            JOptionPane.showMessageDialog(null, panel, title, JOptionPane.PLAIN_MESSAGE, icon);
               
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BarPanel = new javax.swing.JPanel();
        ProgressBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        packageNameTxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listOfFiles = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noOfFiles = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        header1.setBackground(new java.awt.Color(0, 0, 0));
        header1.setForeground(new java.awt.Color(169, 224, 49));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton12.setToolTipText("Close");
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton12.setVerifyInputWhenFocusTarget(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        header1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        header1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/metrics 64.png"))); // NOI18N
        jLabel1.setText("  Source Code Metrics Visualizer of JAVA");
        header1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        BarPanel.setBackground(new java.awt.Color(0, 0, 0));

        ProgressBar.setBackground(new java.awt.Color(0, 0, 0));
        ProgressBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProgressBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loadingBar.gif"))); // NOI18N

        javax.swing.GroupLayout BarPanelLayout = new javax.swing.GroupLayout(BarPanel);
        BarPanel.setLayout(BarPanelLayout);
        BarPanelLayout.setHorizontalGroup(
            BarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(BarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BarPanelLayout.createSequentialGroup()
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BarPanelLayout.setVerticalGroup(
            BarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(BarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BarPanelLayout.createSequentialGroup()
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        header1.add(BarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packageNameTxt.setEditable(false);
        packageNameTxt.setColumns(20);
        packageNameTxt.setRows(5);
        jScrollPane3.setViewportView(packageNameTxt);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, 490, 40));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setText("Browse Package");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 55, 180, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backRollOver.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 40, 40));

        listOfFiles.setMaximumSize(new java.awt.Dimension(33, 500));
        listOfFiles.setMinimumSize(new java.awt.Dimension(33, 500));
        listOfFiles.setPreferredSize(new java.awt.Dimension(33, 500));
        listOfFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOfFilesMouseClicked(evt);
            }
        });
        listOfFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listOfFilesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listOfFiles);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 150, 490, 330));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Names Of Files");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 490, 45));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("No. Of Files :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 115, 130, 45));

        noOfFiles.setEditable(false);
        noOfFiles.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        noOfFiles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noOfFiles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        noOfFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfFilesActionPerformed(evt);
            }
        });
        jPanel1.add(noOfFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 115, 45, 45));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton3.setText("Count Metrics");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(750, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        ClearTables();
         m.removeAllElements();
         listOfFiles.removeAll();
         packageNameTxt.setText(null);
         noOfFiles.setText(null);
         
         // select Java package              
          JFileChooser  chooser = new JFileChooser();
          chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
          int result= chooser.showOpenDialog(this);
          File f = chooser.getCurrentDirectory();
         
          
          if (result == JFileChooser.APPROVE_OPTION) {
          
          selectedPackageName= chooser.getSelectedFile().getAbsolutePath();      
          selectJavaPackage();
          insertClassNameToDB();
          }
         // These are created to show that our CBO function is working
        BrowseJavaFile bf1,bf2=new BrowseJavaFile();
        JavaPackageMetrics jpm1,jpm2,jpm3=new JavaPackageMetrics();
        SignInUp sp=new SignInUp();
        ForgetPassword fp=new ForgetPassword();
        Dashboard bd1,db2=new Dashboard();
        ChangePassword cp1,cp2=new ChangePassword();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listOfFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOfFilesMouseClicked
       selected=listOfFiles.getSelectedValue().toString();
       fileName=extractFileName(selected);    
    }//GEN-LAST:event_listOfFilesMouseClicked

    private void listOfFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listOfFilesValueChanged

    }//GEN-LAST:event_listOfFilesValueChanged

    private void noOfFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfFilesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   BarPanel.setVisible(true);    
        // TODO add your handling code here:
        if(selected==null){
             AlertMessage("Please Select a File For Counting Metrics!!!","src/images/close.png"," Alert!!!");
        }else{
         JavaPackageMetrics c=new JavaPackageMetrics(selected,fileName,alist,selectedPackageName); 
         c.setVisible(true);
           BarPanel.setVisible(false);    
         this.dispose();
        }
          BarPanel.setVisible(false);    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         GoodBye gb=new GoodBye();
        gb.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    String fg;
     public void openDBConnection(){
        try{
        Database db=new Database();
        con=db.openConnection();
        }catch(HeadlessException| SQLException e){
            JOptionPane.showMessageDialog(null, "DB not connected");
        }
    }
     public void selectJavaPackage(){
         
          packageNameTxt.setText(selectedPackageName);
    try {
        listFilesAndFilesSubDirectories(selectedPackageName);
    } catch (IOException ex) {
        Logger.getLogger(BrowseJavaPackage.class.getName()).log(Level.SEVERE, null, ex);
    }
       listOfFiles.setModel(m);
       int a=m.getSize();
       noOfFiles.setText(String.valueOf(a));
          
    }
     public static String extractFileName( String filePathName ){
    if ( filePathName == null )
      return null;

    int dotPos = filePathName.lastIndexOf( '.' );
    int slashPos = filePathName.lastIndexOf( '\\' );
    if ( slashPos == -1 )
      slashPos = filePathName.lastIndexOf( '/' );
    if ( dotPos > slashPos )
    {
      return filePathName.substring( slashPos > 0 ? slashPos + 1 : 0,
          dotPos );
    }
    return filePathName.substring( slashPos > 0 ? slashPos + 1 : 0 );  
  }
    public void listFilesAndFilesSubDirectories(String directoryName) throws IOException{
        File directory = new File(directoryName);

        //get all the files from a directory
        File[] fList = directory.listFiles(new FileFilter(){
               public boolean accept (File pathname){
                   String st=pathname.getName();
                   if(pathname.isDirectory()||st.endsWith(".java"))
                return true;
               else
               return false;    
               } });
        
        for (File file : fList){
            if (file.isFile()){
            String ad=file.getCanonicalPath();
                   m.addElement(ad);
                   fg=extractFileName(ad);
                   alist.add(fg);  
            }    
            else if (file.isDirectory()){
                listFilesAndFilesSubDirectories(file.getAbsolutePath());
            }
        }
    }
    public void insertClassNameToDB(){
         String query="INSERT INTO `classnamestbl`(`c_name`) VALUES (?);";
            try {             
                pstm=con.prepareStatement(query);
                for(String name: alist){
                pstm.setString(1,name);            
                pstm.execute();
                }
            } catch (SQLException ex) {
                Logger.getLogger(BrowseJavaPackage.class.getName()).log(Level.SEVERE, null, ex);
            }       
    }
    public void ClearTables(){
         try {
            // TODO add your handling code here:
            pstm=con.prepareStatement("delete  from classnamestbl");
            pstm.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(BrowseJavaPackage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseJavaPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseJavaPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseJavaPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseJavaPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowseJavaPackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarPanel;
    private javax.swing.JLabel ProgressBar;
    private javax.swing.JPanel header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listOfFiles;
    private javax.swing.JTextField noOfFiles;
    private javax.swing.JTextArea packageNameTxt;
    // End of variables declaration//GEN-END:variables
}
